# -*- coding: utf-8 -*-
"""AULA 7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aU15UsnsO117CTc8CY5sgdr-WV2lk49O
"""

def soma ():
  print("1+2")
soma()
#função pesquisar

senha_correta = "123"
Chances = 3

while Chances > 0:
  senha = input("Digite uma senha ")
  if senha == senha_correta:
    print("Pode acessar")
    break
  else:
    Chances -= 1
    print("Erro de digitação")
  if Chances == 0:
    print("Suas chances acabaram")

contador = 10

while contador > 0:
  print(contador)
  contador -=1
  print("Contagem", contador)
  #and == true
  #or qualquer uma for true ele vai fazer

#exer 1
contador = 10

while contador > 0:
  print(contador)
  contador -=1
  print("Contagem", contador)
if contador == 0:
  print("FOGO")
else:
   print("Contagem", contador)

#exer 2

#JOGO
import random
x = random.randint(1, 15)
chute = int (input("Digite um número inteiro entre 1 e 15 "))
if chute == x:
  print("Parabéns", x)
else:
  print("Errou o número é: ", x)